### ISSUE TITLE
Sort out the main page 

### ISSUE THREAD

**Issue by rerpha** [ISISComputingGroup/WebDashboard#34]
As a user of the dashboard I would like the content on the main page (https://github.com/ISISComputingGroup/WebDashboard/blob/main/app/page.tsx) to actually make sense. currently this is lorem ipsum/chatgpt output and doesn't read that well. we should make it better! 

I think the layout is fine, so just the content ie. https://github.com/ISISComputingGroup/WebDashboard/blob/main/app/page.tsx#L251-L255 needs to be changed. there is also a lot of commented-out code in that file, this should be removed. 

### acceptance criteria 
- [ ] Content is much more concise and accurate
- [ ] Commented code is removed

**Comment by KarynMC27** [comment]
I'll work on this.

**Comment by KarynMC27** [comment]
Pull request here: https://github.com/ISISComputingGroup/WebDashboard/pull/40
