### ISSUE TITLE
Web dashboard: display setpoint as well as current value

### ISSUE THREAD

**Issue by Tom-Willemsen** [ISISComputingGroup/WebDashboard#56]
As an instrument scientist or developer, I would like to see the setpoint as well as the readbacks for my blocks (if the setpoint exists). This would help with diagnostics.

See how the seci dataweb does this:

![image](https://user-images.githubusercontent.com/24375813/39618471-c809c9aa-4f7b-11e8-9b93-88664af0efcb.png)

**Comment by rerpha** [comment]
this shouldn't be hard as we already subscribe to run control enabled/in range PVs for each block anyway, so just need to look at how that logic works.
