### ISSUE TITLE
Feature request: formatting of PV values as fixed-format or scientific numbers 

### ISSUE THREAD

**Issue by mducle** [ISISComputingGroup/WebDashboard#78]
At the moment the formatting of the PV values in the WebDashboard is a bit haphazardous (also it seems that some PVs return `String` for numeric values and some return `Number`s making it even more confusing). For example on [MARI](https://isiscomputinggroup.github.io/WebDashboard/instrument?name=mari), the `Fermi_speed` is given in scientific notation but is always an integer less than `1000` so would be more readable displayed as an integer, whilst the `Tank_Pressure` is displayed in fixed-format but is usually a very small number (around `1e-5`) when the instrument is running so would be better displayed using scientific notation.

Could these numbers be formatted so that very large (e.g. greater than `10000`) and very small (less than `0.001`) values be shown in scientific notation whilst everything else is in fixed-format?

**Comment by Tom-Willemsen** [comment]
For comparison, [here ](https://github.com/ISISComputingGroup/ibex_gui/blob/4d49a3113412c11abcbf9c6c00fc0972a2668884/base/uk.ac.stfc.isis.ibex.epics.tests/src/uk/ac/stfc/isis/ibex/epics/tests/conversion/ExponentialOnThresholdFormatTest.java#L83)are the unit tests for the numeric formatting in the IBEX GUI..

I think a good way to approach this ticket would be to port-in those unit tests, then match the behaviour of the GUI as closely as possible.

**Comment by mducle** [comment]
@Tom-Willemsen Ok. I'll look into that code.

**Comment by Tom-Willemsen** [comment]
Fixed by https://github.com/ISISComputingGroup/WebDashboard/pull/79
